-- See https://stevedonovan.github.io/ldoc/manual/doc.md.html
file = "jls"
project = "JLS"
title = "Lua JLS 0.3"
description = "Lua JLS"
full_description = "The jls Lua libraries provide abstraction interfaces for general-purpose scripting"
--no_summary = true
--no_space_before_args = true 
--sort = true
--style = "!fixed"
no_lua_ref = true
topics = "doc_topics"
package = "jls"
--format = "discount"
format = "markdown"